version: "3.9"
services:

  authapi: 
    image: ghcr.io/thewatergategroups/authapi
    command: python -m authapi api
    depends_on:
      - dbsetup
    volumes:
      - ./authapi:/app/authapi
      - ./templates:/app/templates
    ports: 
      - 8000:8000
    env_file:
      - .env
    
  dbsetup: 
    image: ghcr.io/thewatergategroups/authapi
    command: python -m authapi db upgrade
    volumes:
      - ./authapi:/app/authapi
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    profiles:
      - pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: chart@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    network_mode: host