version: "3.9"
services:

  authapi: 
    image: authapi
    command: python -m authapi api
    depends_on:
      - dbsetup
    volumes:
      - ./authapi:/app/authapi
    env_file:
      - .env
    network_mode: host
 
  dbsetup: 
    image: authapi
    command: python -m authapi db upgrade
    volumes:
      - ./authapi:/app/authapi
    env_file:
      - .env
    network_mode: host
