# pylint: disable=all
"""

Revision ID: 602f0fa2aec4
Revises: 4c15bf461b81
Create Date: 2024-04-07 19:18:00.179543

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "602f0fa2aec4"
down_revision: Union[str, None] = "4c15bf461b81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authorization_codes",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("scopes", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("code_challenge", sa.String(), nullable=True),
        sa.Column("code_challenge_method", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"], ["auth.clients.id_"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("code"),
        schema="auth",
    )


def downgrade() -> None:
    op.drop_table("authorization_codes", schema="auth")
