"""add_certs

Revision ID: 6246ce2fa579
Revises: 27bd1d973b2d
Create Date: 2023-12-26 18:43:10.490436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from authapi.schemas import Alg
from sqlalchemy import orm

# revision identifiers, used by Alembic.
revision: str = "6246ce2fa579"
down_revision: Union[str, None] = "27bd1d973b2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certs",
        sa.Column("alg", sa.String(), nullable=False),
        sa.Column("cert", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("alg"),
        schema="auth",
    )
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    for alg in Alg:
        alg.insert_cert(session, alg.generate_private_key())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("certs", schema="auth")
    # ### end Alembic commands ###
