# pylint: disable=all
"""

Revision ID: 882caf233a8d
Revises: 4c15bf461b81
Create Date: 2024-04-07 22:06:52.196471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "882caf233a8d"
down_revision: Union[str, None] = "4c15bf461b81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authorization_codes",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("scopes", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("code_challenge", sa.String(), nullable=True),
        sa.Column("code_challenge_method", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"], ["auth.clients.id_"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("code", "user_id"),
        schema="auth",
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id_", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("scopes", sa.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"], ["auth.clients.id_"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id_"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_", "user_id"),
        schema="auth",
    )

    op.add_column(
        "users",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at", schema="auth")
    op.drop_table("refresh_tokens", schema="auth")
    op.drop_table("authorization_codes", schema="auth")
    # ### end Alembic commands ###
