"""add client tabels

Revision ID: f0bbc3d57aa6
Revises: 6246ce2fa579
Create Date: 2024-02-23 07:31:14.262076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f0bbc3d57aa6"
down_revision: Union[str, None] = "6246ce2fa579"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id_", sa.Uuid(), nullable=False),
        sa.Column("secret_hash", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id_"),
        schema="auth",
    )
    op.create_table(
        "client_grants",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("grant_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["auth.clients.id_"],
        ),
        sa.PrimaryKeyConstraint("client_id", "grant_type"),
        schema="auth",
    )
    op.create_table(
        "client_redirect_uris",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["auth.clients.id_"],
        ),
        sa.PrimaryKeyConstraint("client_id", "redirect_uri"),
        schema="auth",
    )
    op.create_table(
        "client_scopes",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["auth.clients.id_"],
        ),
        sa.ForeignKeyConstraint(
            ["scope"],
            ["auth.scopes.id_"],
        ),
        sa.PrimaryKeyConstraint("client_id", "scope"),
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("client_scopes", schema="auth")
    op.drop_table("client_redirect_uris", schema="auth")
    op.drop_table("client_grants", schema="auth")
    op.drop_table("clients", schema="auth")
    # ### end Alembic commands ###
