apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authapi
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: authapi
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /authapi
  # data:
    # - secretKey: SALT
    #   remoteRef:
    #     key: /authapi
    #     property: SALT  # This is the JSON key inside your stored JSON object
    # - secretKey: LOG_LEVEL
    #   remoteRef:
    #     key: /authapi
    #     property: LOG_LEVEL
    # Add more entries similar to above for each property you need
