apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authapi-ext
  namespace: default  # Adjust the namespace as per your setup
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: SecretStore
  target:
    name: authapi-ext
    creationPolicy: Owner
  # If you want to fetch all data as a single secret uncomment below
  dataFrom:
    - extract:
        key: /authapi
  # data:
    # - secretKey: SALT
    #   remoteRef:
    #     key: /authapi
    #     property: SALT  # This is the JSON key inside your stored JSON object
    # - secretKey: LOG_LEVEL
    #   remoteRef:
    #     key: /authapi
    #     property: LOG_LEVEL
    # Add more entries similar to above for each property you need
