apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authapi-ingress
  annotations:
    external-dns.alpha.kubernetes.io/alias: "true"
    external-dns.alpha.kubernetes.io/target: "thewatergategroups.com"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - auth.thewatergategroups.com
    secretName: wildcard-watergate-tls
  rules:
  - host: auth.thewatergategroups.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authapi
            port:
              number: 8000
