---
# Source: auth/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authapi
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    
type: Opaque
stringData:
{{- toYaml .Values.secrets  | nindent 2 }}