
imageName: ghcr.io/1ndistinct/authapi:latest

regCredName: regcred

secrets:
  SALT: <SECRET> 
  LOG_LEVEL: INFO
  PGHOST: <SECRET>
  PGDATABASE: <SECRET>
  PGPASSWORD: <SECRET>
  PGUSER: <SECRET>
  DB_SCHEMA: auth