on:
  push:
    branches:
      - dev
      - main

jobs:
  Python:
    uses: 1ndistinct/ops/.github/workflows/python-docker-workflow.yaml@master
    secrets:
      CONTAINER_PAT: ${{ secrets.CONTAINER_PAT }}
      PYPI_USER: ${{ secrets.PYPI_USER }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}